config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  resources :lyrics, :tracks, :albums, :artists
  
  get "/search", to: "search#search"
end

app/models/album.rb
class Album < ActiveRecord::Base

  belongs_to :artist
  has_many :tracks

  def year
    release_year.try(:year)
  end

  def participating_artists
    tracks.collect {|t| t.participating_artists }.flatten.uniq
  end
  
  def principal_artist
    participating_artists.select {|pa| pa.principal? }.uniq.first
  end
  
  def update_spotify_uri
    update_attribute :spotify_uri, spotify_record.try(:uri) if !spotify_uri
  end
  
  def spotify_record
    MetaSpotify::Album.search("#{title} #{principal_artist.try(:name)}")[:albums].first
  end
  
  def self.searchable_language
    'spanish'
  end
  
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :tracks, through: :track_participations
  has_many :track_participations
  
  def update_spotify_uri
    update_attribute :spotify_uri, spotify_record.try(:uri) if !spotify_uri
  end
  
  def spotify_record
    MetaSpotify::Artist.search(name)[:artists].first
  end
  
  def self.searchable_language
    'spanish'
  end
  
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/lyric.rb
class Lyric < ActiveRecord::Base
  include ActionView::Helpers::TextHelper
  include ActiveSupport::Inflector

  include PgSearch
  multisearchable :against => [:body]
    
  has_many :tracks, -> {select('tracks.*, lyric_occurences.position')}, through: :lyric_occurences
  has_many :lyric_occurences
  
  scope :completed, -> { where("body NOT LIKE '(%'") }

  def has_audio?
    tracks.any? {|t| t.has_audio? }
  end
  
  def self.random
    order("RANDOM()").limit(1).first
  end
  
  def self.searchable_language
    'spanish'
  end
  
end

app/models/lyric_occurence.rb
class LyricOccurence < ActiveRecord::Base  
  belongs_to :track
  belongs_to :lyric
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  has_many :participating_artists, -> {select("artists.*, principal, role")},
                                   through: :track_participations, source: :artist
  has_many :track_participations
  has_many :lyrics, -> {select('lyrics.*, position, spotify_offset').order('position')},
                    through: :lyric_occurences
                    
  has_many :lyric_occurences
  
  def has_audio?
    audio_url
  end
  
  def derived_title
    return title if title
    style
  end
  
  def principal_artist
    participating_artists.detect {|a| a.principal? }
  end
  
  def complete_style
    txt = ""
    if palo
      txt << palo
    end
    if style
      if palo
        txt << ", "
      end
      txt << style
    end
  end
  
  def update_spotify_uri
    update_attribute :spotify_uri, spotify_record.try(:uri) if !spotify_uri
  end
      
  def spotify_record
    MetaSpotify::Track.search("#{title} #{album.title}")[:tracks].first  
  end
  
  def singer
    track_participations.detect {|a| a.role == "cante" }.try :artist
  end
  
  def guitarist
    track_participations.detect {|a| a.role == "guitarra" }.try :artist
  end

  def self.searchable_language
    'spanish'
  end
end

app/models/track_participation.rb
class TrackParticipation < ActiveRecord::Base  
  belongs_to :track
  belongs_to :artist
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  def index
    @albums = Album.order("title")
  end
  
  def show
    @album = Album.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter do
    path = request.path == "/" ? "lyrics" : request.path 
    redirect_to "http://tomaflamenco.com/es/#{path}", status: :moved_permanently
  end
    
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  
  def index
    @artists = Artist.order("name")
  end
  
  def show
    @artist = Artist.find params[:id]
  end
  
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
  def index
    @lyrics = Lyric.completed.order(:body).page(params[:page]).per(50)
  end
  
  def show
    @lyric = Lyric.find params[:id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @lyric = Lyric.random
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @results = Kaminari.paginate_array(PgSearch.multisearch(params[:q]).to_a).page(params[:page] || 1)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  
  def index
    Track.all
  end
  
  def show
    @track = Track.find params[:id]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def occurrences_for(lyric)
    lyric.lyric_occurences.collect do |lo|
      "<i>#{lo.track.palo}</i> de  por  en #{link_to lo.track.title, lo.track}}"
    end.join("<br />")
  end

  def poetic_lyric(lyric)
    lyric.body.gsub("\n", "<br />").html_safe
  end
  
  def audio_for(track)
    if track.has_audio?
      "<audio style=\"margin-top: 5px\" controls>
        <source src=\"#{track.audio_url}\" type=\"audio/mpeg\">
      Your browser does not support the audio element.
      </audio>"
    end
  end
end

app/helpers/lyrics_helper.rb
module LyricsHelper
end

app/views/albums/index.html.erb
<ul>
<% @albums.each do |album| %>
<li><%= link_to album.name, album_path(album) %></li>
<% end %>
</ul>

app/views/albums/show.html.erb
<div class="large-6 columns">
<h1 style="font-size: 130%"><%= @album.title %></h1>
<% if !@album.compilation? %>
  <% @album.participating_artists.each do |artist| %>
  <h3 style="font-size: 120%"><%= link_to artist.name, artist_path(artist) %></h3>
  <% end %>
<% end %>

<ul>
  <% @album.tracks.each do |t| %>
  <li><%= link_to t.title, track_path(t) %></li>
  <% end %>
</ul>
</div>

<div class="large-6 columns">
<% if @album.spotify_uri %>
<iframe src="https://embed.spotify.com/?uri=<%= @album.spotify_uri %>" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
<% end %>
</div>

app/views/artists/index.html.erb
<ul>
<% @artists.each do |artist| %>
<li><%= link_to artist.name, artist_path(artist) %></li>
<% end %>
</ul>

app/views/artists/show.html.erb
<div style="float: left; width: 49%">
<h1><%= @artist.name %></h1>
<ul>
  <% @artist.tracks.each do |t| %>
  <li><%= link_to t.derived_title, track_path(t) %></li>
  <% end %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Letras</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "vendor/custom.modernizr" %>
  
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="//use.typekit.net/vow4ond.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
</head>
<body>
<div class="row" id="header">
  <div class="large-centered" style="text-align: center; margin-bottom: 30px">
  <%= link_to "Ver todas las letras", lyrics_path, style: "font-size: 80%" %>
  </div>
  
  <div class="large-8 large-centered columns" id="header">
    <div class="row collapse">
      <form action="/search" method="get">
        <div class="large-10 columns">
          <input type="text" name="q" placeholder="<%= "Buscar una letra aquí" %>" value="<%=params[:q]%>">          
        </div>
        <div class="large-2 columns">
          <input type="submit" value="Buscar" class="button small" id="search_button">
        </div>
      </form>
    </div>
  </div>
</div>
<div class="row" id="content">
  <%= yield %>
</div>

<script type="text/javascript">
var clicky_site_ids = clicky_site_ids || [];
clicky_site_ids.push(100631056);
(function() {
  var s = document.createElement('script');
  s.type = 'text/javascript';
  s.async = true;
  s.src = '//static.getclicky.com/js';
  ( document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0] ).appendChild( s );
})();
</script>
<noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/100631056ns.gif" /></p></noscript>
</body>
</html>

app/views/lyrics/index.html.erb
<div class="pagination">
  <%= paginate @lyrics %>
</div>

<ul>
<% @lyrics.each do |l| %>
<li><%= link_to l.body.gsub("\n", " / "), lyric_path(l) %></li>
<% end %>
</ul>

<div class="pagination">
  <%= paginate @lyrics %>
</div>

app/views/lyrics/show.html.erb
<div class="row">
<p class="lyric large-6 columns" style="font-size: 180%"><%=raw @lyric.body.gsub("\n", "<br />")  %></p>
<div class="large-6 columns">
  <ul class="appearances">
  <% @lyric.tracks.each do |track| %>
  <li style="margin-bottom: 10px">
    <div class="track_title">
  <%= link_to track.title, track_path(track) %>
    </div>
    <% if track.principal_artist %>
    <div style="font-size: 80%" class="artist_name">
      <%= link_to track.principal_artist.name, artist_path(track.principal_artist) %>
    </div>
    <% end %>
    <div  style="font-size: 80%" class="album_title">
      <%= link_to track.album.title, album_path(track.album) %>
    </div>
    <p>verso #<%= track.position + 1 %></p>
    <% if track.spotify_uri %>
     <iframe src="https://embed.spotify.com/?uri=<%= track.spotify_uri%>&view=coverart&theme=white" frameborder="0" allowtransparency="true"></iframe>
     <% end %>
  </li>
  <% end %>
  </ul>
</div>
</div>

app/views/pages/home.html.erb
<div class="row">
  <div class="large-centered large-6 columns">
    <p id="home_lyric"><%= poetic_lyric(@lyric) %></p>
    <p><em><%= @lyric.tracks.first.style %></em>
     
      <% if @lyric.tracks.first.principal_artist %>
      <h2 style="font-size: 90%"><%= link_to @lyric.tracks.first.principal_artist.name, artist_path(@lyric.tracks.first.principal_artist) %></h2>
      <% end %>

      <% if @lyric.tracks.first %>
      <h3 style="font-size: 75%"><%= link_to @lyric.tracks.first.title, track_path(@lyric.tracks.first) %></h3>
      <% end %>

      <% if @lyric.tracks.first.album %>
      <h3 style="font-size: 75%"><%= link_to @lyric.tracks.first.album.title, album_path(@lyric.tracks.first.album) %>
        <% if release_year = @lyric.tracks.first.album.year %>
        (<%= release_year %>)
        <% end %></h3>
      <% end %>
  </div>
</div>

app/views/search/search.html.erb
<% if !@results.empty? %>
<div class="pagination">
  <%= paginate @results %>
</div>
<ul class="large-block-grid-3" id="search-results">
<% @results.each do |r| %>
  <% l = Lyric.find(r.searchable_id)%>
  <li class="lyric_result">
    <p><%= link_to highlight(l.body.gsub("\n", "<br />"), params[:q]), lyric_path(l)  %></p>
    <% l.lyric_occurences.each do |lo| %>
    <h4><%= lo.track.style %></h4>
    <% if lo.track.singer %>
      <h5><%= link_to lo.track.singer.name, artist_path(lo.track.singer) %></h5>
    <% end %>
    <div class="track">
      <%= link_to lo.track.title, track_path(lo.track) %>
      <% if lo.track.spotify_uri %>
        <% link_to 'Spotify', lo.track.spotify_uri %>
      <% end %>
    </div>
    <div class="album"><%= link_to lo.track.album.title, album_path(lo.track.album) %>
      <% if year = lo.track.album.year %>
      , <%= year %>
      <% end %>
      <% if lo.track.album.spotify_uri %>
        , <% link_to 'Spotify', lo.track.album.spotify_uri %>
      <% end %>
      </div>
    <% end %>
  </li>
<% end %>
</ul>
<div class="pagination">
  <%= paginate @results %>
</div>
<% else %>
<h2>No hay resultados!</h2>
<% end %>

app/views/tracks/show.html.erb
<div class="large-6 columns">
  <h1 style="font-size: 150%"><%= @track.title %></h1>
  <h2 style="font-size: 140%"><%= @track.style %></h2>
  <h3 style="font-size: 130%"><%= link_to @track.album.title, album_path(@track.album) %></h3>

  <h3 style="font-size: 120%">
    <%= @track.participating_artists.collect { |artist| link_to(artist.name, artist_path(artist)) }.join(", ").html_safe %></h3>

  <div style="margin-top: 50px">
    <% @track.lyrics.each do |l| %>
    <p style="font-size: 120%">
      <%=raw l.body.gsub("\n", "<br />") %>
    </p>

    <% end %>
  </div>
</div>
<div class="large-6 columns">
  <% if @track.spotify_uri %>
  <iframe src="https://embed.spotify.com/?uri=<%= @track.spotify_uri%>&view=coverart&theme=white" frameborder="0" allowtransparency="true"></iframe>
  <% end %>
</div>